import Head from "next/head";
import {
  createStyles,
  makeStyles,
  useTheme,
  Theme,
} from "@material-ui/core/styles";
import Header from "../../src/components/header";
import Sidebar from "../../src/components/sidebar";
import TodoList from './todo-list';

const useStyles = makeStyles((theme: Theme) =>
  createStyles({
    root: {
      display: "flex",
    },
    toolbar: {
      display: "flex",
      alignItems: "center",
      justifyContent: "flex-end",
      padding: theme.spacing(0, 1),
      // necessary for content to be below app bar
      ...theme.mixins.toolbar,
    },
    content: {
      flexGrow: 1,
      padding: theme.spacing(3),
    },
  }))

export default function Home() {
  const classes = useStyles();
  const theme = useTheme();

  return (
    <div className={classes.root}>
      <Head>
        <title> Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Sidebar/>

      <main className={classes.content}>

        <div className={classes.toolbar} />
          <TodoList/>
      </main>

    </div>
  );
}
